### ISSUE TITLE
Cambiar Iconos por corporativos

### ISSUE THREAD

**Issue by elalek** [andydockett/turismo_app#10]
Adjunto propuesta, faltaría icono de VIDA NOCTURNA, los archivos SVG se encuentran en:
https://drive.google.com/drive/folders/1B6kcTh8wUlY-yxix9llehRlIlFVrQMGT?usp=sharing

por otra parte se adjunta el archivo ilustrator en caso de que hagan falta algunos, 

si hay algún icono que necesita ser corregido, favor de solicitar.

si necesitan algun icono que no exista, favor de solicitar.

**Comment by andydockett** [comment]
En proceso
