### ISSUE TITLE
Buscador

### ISSUE THREAD

**Issue by felipeossandonvlpo** [andydockett/turismo_app#27]
A la palabra "Buscador" al desplegar el menú, le asociaría una lupa. Pero antes que eso, pondría el buscador afuera, quizás abajo del ícono que despliega el menú.
También hecho de menos un buscador en cada una de las secciones. Hasta ahora solo veo filtros de búsqueda, pero creo que todas deberían tener un buscador para búsqueda por palabra.

**Comment by andydockett** [comment]
agregado en versión 1.2
